### ISSUE TITLE
Update pip package

### ISSUE THREAD

**Issue by scls19fr** [python-constraint/python-constraint#10]
Hi @niemeyer ,

it will be nice if you could update package on PyPi.
https://pypi.python.org/pypi/python-constraint

Best regards

Sébastien

**Comment by scls19fr** [comment]
Pinging @niemeyer

**Comment by agriffis** [comment]
Hi @scls19fr and @niemeyer 

It would be great if the improvements in this repository could be released on PyPI! However as far as I can tell, this repo is a fork of the original package, without engagement by @niemeyer or privs to update on PyPI.

It seems like the easiest path forward would be for @niemeyer to add @scls19fr as a maintainer (or owner) on PyPI.  do that, @niemeyer logs in at https://pypi.python.org/ then navigate to the python-constraint package, click roles and add `scls19fr`.

If @niemeyer is unresponsive, then @scls19fr could file a support request at https://sourceforge.net/p/pypi/support-requests/ to have the package ownership transferred. Naturally this should only be after exhausting all options to communicate with @niemeyer. Alternatively @scls19fr could register a forked name on PyPI such as `python-constraint2`, but that's less desirable because it's confusing to users.

What do you think?

**Comment by scls19fr** [comment]
I'd prefer not to register a "python-constraint2" under PyPI.

**Comment by agriffis** [comment]
Coming back to this after a long time, just sent email to @niemeyer to see if we can get this unstuck:

> Hi Gustavo,
> 
> Would you consider adding scls19fr as a maintainer on PyPI so he could upload new versions?
> 
> https://github.com/python-constraint/python-constraint/issues/10#issuecomment-257582226
> 
> Thanks,
> Aron

**Comment by agriffis** [comment]
![screenshot from 2017-03-11 18-46-01](https://cloud.githubusercontent.com/assets/50637/23827827/0bb67bde-068b-11e7-8d18-79722f9e76ed.png)

**Comment by niemeyer** [comment]
Worked. :)

**Comment by niemeyer** [comment]
Getting this error when trying to add you to python-constraint in pypi:
```
Error processing form

user doesn't exist
```

**Comment by niemeyer** [comment]
This was with `scls19fr`, as suggested above. What's your username there, @scls19fr?

**Comment by agriffis** [comment]
@niemeyer Thanks so much for jumping in. :-)

It would be better if @scls19fr confirms, but I can see at https://pypi.python.org/pypi/pandas_degreedays/ that his username on PyPI is "scls"

**Comment by scls19fr** [comment]
Hi @niemeyer , hi @agriffis 

@agriffis is right my username on PyPi is scls

On the GitHub side @niemeyer is collaborator with admin rights and @agriffis is member

Invitations are sent via email and can be accepted at https://github.com/python-constraint

Kind regards

**Comment by niemeyer** [comment]
@scls19fr You're in as maintainer in pypi. Please let me know if I can help further.

**Comment by scls19fr** [comment]
Thanks @niemeyer 
@agriffis I will try to upload a newer version ... but it will be only in the end of march or beginning of april
because I'm quite busy these days.

**Comment by scls19fr** [comment]
1.3 release published on PyPi.
Thanks @agriffis and @niemeyer
